### ISSUE TITLE
Your Sniffers

### ISSUE THREAD

**Issue by rrodrigofranco** [Hermann-SW/wireless-control-Eachine-E52-drone#4]
Hello, I really liked your project, but I'm having trouble capturing the hex codes of my drone, because the video sends signals through the TCP protocol and there are several signals! The model of my drone is the JJRC h68 which is different from yours, so I would like you to send me your sniffers that you captured from the wireshark so I can try to identify which hex codes I should get for you for the drone video to work.

**Comment by Hermann-SW** [comment]
I used Ettercap MITM to capture th traffic, described in this section:
https://github.com/Hermann-SW/wireless-control-Eachine-E52-drone#capturing-wireless-traffic-between-android-ufo-app-and-e52-drone
